### ISSUE TITLE
pyinstaller打包后的exe执行两次

### ISSUE THREAD

**Issue by Ppsoft1991** [Ridter/RelayX#2]
![图片](https://github.com/Ridter/RelayX/assets/18442117/08c245df-31f6-418a-93c3-5e695239c670)
使用pyinstaller.exe -F .\relayx.py --hidden-import unicrypto.backends.pycryptodomex 命令打包relayx会存在执行两次的bug

**Comment by Ridter** [comment]
已修复，可以参考`README.md`里面的编译方法进行编译使用。
